### ISSUE TITLE
Version not getting bumped properly from Foundry

### ISSUE THREAD

**Issue by Kallaide** [skepickle/foundryvtt-gaming-table-player#10] opened 2022-12-03 01:21 UTC
Seems the readme version is still telling Foundry to keep it at 0.8 instead of updating it to 1.02. Any time I have foundry update the modules, it will download Gaming Table Player but keep it at 0.8

Had to come here and download it manually to get the newer version

**Comment by skepickle** [comment] 2022-12-03 01:50
Readme version? Where's the version in the readme?
Is your world in hosted in Foundry running FoundryVTT v9? or have you upgraded to v10?

**Comment by skepickle** [comment] 2022-12-03 01:52
![image](https://user-images.githubusercontent.com/3783101/205416909-f87d139b-e187-481b-bb84-2004eadd289c.png)
Looking at the above, it looks like to me that you are running Foundry v9 most likely. This module only supports v10 of Foundry from 1.0.0 onward.

**Comment by skepickle** [comment] 2022-12-05 21:07
@Kallaide please let me know if you are running FoundryVTT v10, as not updating would definitely be some sort of bug then. But if you are running v9, then this is expected behavior.

**Comment by Kallaide** [comment] 2022-12-06 00:09
Hey sorry for the late reply, I'm on Version 10 and hosted on my own server.

Not sure how I got the v.8, pretty sure it was from inside Foundry but I could be wrong. Either way, every time it went to upgrade it would just say, v0.8 upgraded to v0.8

**Comment by Kallaide** [comment] 2022-12-06 00:11
It wasn't until I downloaded the newer version from GitHub and replaced the one on my server that Foundry recognized it as the new version and didn't try to update it.

**Comment by skepickle** [comment] 2022-12-06 20:17
Hm. I'm going to have to try and reproduce this on my server. I'm not sure what might be wrong.

**Comment by skepickle** [comment] 2023-01-07 20:15
I found the problem @Kallaide. Should be fixed in 1.0.3!

**Closed as completed** 2023-01-07 20:17 UTC
Labels: bug

**Comment by Kallaide** [comment] 2023-01-08 18:39
Awesome! Glad you were able to find the issue and I wasn't just crazy lol
